[package]
name = "rust"
version = "0.1.0"
authors = ["lambrospetrou <lambrospetrou@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
rusqlite = "0.24.1"
