app = "green-moon-7086"

kill_signal = "SIGINT"
kill_timeout = 5

[env]
  SQLITE_PATH = "/db/users.db"

[mounts]
  source="data_db"
  destination="/db"

[[services]]
  internal_port = 5000
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 500
    soft_limit = 20

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "5s"
    timeout = "2s"
    # By default it restarts infinitely, so specify no restart to fail the deployment.
    restart_limit = 0
